name: wallet
description: A modern Flutter Wallet App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ----------------------------
  # STATE MANAGEMENT
  # ----------------------------
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

  # ----------------------------
  # LOCAL STORAGE
  # ----------------------------
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^10.0.0

  # ----------------------------
  # UI / ANIMATION
  # ----------------------------
  flutter_animate: ^4.5.0
  fl_chart: ^1.1.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.0.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # ----------------------------
  # FILES / PERMISSIONS
  # ----------------------------
  permission_handler: ^12.0.1
  open_file: ^3.3.2
  csv: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.11.1
  isar_generator: ^3.1.0+1
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/Product Sans Regular.ttf
        - asset: assets/fonts/ProductSans/Product Sans Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans/Product Sans Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans/Product Sans Bold Italic.ttf
          weight: 700
          style: italic

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPro/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFPro/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFPro/SFUIDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFPro/SFUIDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFPro/SFUIDisplay-Thin.otf
          weight: 100
        - asset: assets/fonts/SFPro/SFUIDisplay-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SFPro/SFUIDisplay-Heavy.otf
          weight: 800
        - asset: assets/fonts/SFPro/SFUIDisplay-Black.otf
          weight: 900

    - family: AppleColorEmoji
      fonts:
        - asset: assets/fonts/Emoji/iOS15.4_Fixed_space.ttf